### PR TITLE
Implement UTF8 Support

### PR DESCRIPTION
**Pull request by martindale**
Replace `slug-component` with `speakingurl`, which offers sane support of UTF8 characters.  Increments version to reflect this change.

### CODE REVIEW

**Comment by yields** [comment]
thanks @martindale i don't really use this module anymore, would you like to maintain it ?

**Comment by martindale** [comment]
Sure, can do.

**Comment by yields** [comment]
@martindale added! :)

**Comment by martindale** [comment]
@yields thanks!  Can you also give me npm publishing permissions?

**Comment by yields** [comment]
screen shot 2014-03-04 at 12 08 40 am

**Comment by martindale** [comment]
+1, thanks. :)

**Pull request merged**
